name: build-and-deploy to S3

on:
  push:
    branches: [ delta-1 ]

build:
  runs-on: ubuntu-latest
  steps:
    # Checks-out  repo under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
    - name: Set up AWS credentials
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        mkdir -p ~/.aws
        touch ~/.aws/credentials
        echo "[default]
        aws_access_key_id = $AWS_ACCESS_KEY_ID
        aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials

    - name: Upload to S3
      run: aws s3 cp GITHUB_SHA s3://${{secrets.AWS_S3_BUCKET}}/ --region us-west-2