name: List Delta Files & Push SQL scripts to Dev S3 bucket..
on: 
  push:
    branches:
      - delta-1

jobs:

  build:
    name: Generate matrix for build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check changed files
        id: diff
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"

          fi
          echo "$DIFF"
          mkdir ./delta
          for files in $DIFF
          do 
            cp $FILE ./delta/
          done 
          ls -a ./delta

          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"

      - name: Copy files to s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: './delta'
          dest: ${{ secrets.AWS_S3_BUCKET }}  

      #- name: AWS S3 Sync Github Action
        #uses: sai-sharan/aws-s3-sync-action@v0.1.0
        #with:
          #access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          #region: 'us-west-2'
          #source: 'build'
          #destination_bucket: ${{ secrets.AWS_S3_BUCKET }}
          #destination_prefix: 'sql'
          # exclude: '.git/*'
          # delete: true
          # quiet: false
