name: List Incremental Files & Push SQL scripts to Dev S3 bucket
on: 
  push:
    branches:
      - delta

jobs:

  generate-matrix:
    name: Generate matrix for build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check changed files
        id: diff
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          if [ $GITHUB_BASE_REF/SQL/ ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF/SQL/ --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF/SQL/ $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF/SQL/ and $GITHUB_SHA"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
          fi
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"